### ISSUE TITLE
Updating managed version to .NET 4.6

### ISSUE THREAD

**Issue by ThadHouse** [robotdotnet/NetworkTables#39]
@jkoritzinsky Would you be opposed to updating the managed version of NetworkTables to require .NET 4.6? Apparently there are some edge cases where the Async locking code can cause a StackOverflow or a deadlock that were fixed in 4.6. There are also a few odd workarounds I have had to do in 4.5.1 that we would not need in 4.6. NetworkTables.Core would stay 4.5.1, which the WPILib is going to continue using, so we don't need an update there as well. The NetStandard versions would stay the same as they currently are however.

EDIT: It would also allow me to just include the AsyncEx package as a dependency instead of copying the source code. For the managed version I think that is fine, as mode use cases for it are deployments that can handle multiple libraries anyway. NetworkTables.Core will keep as one file as it makes copying to the RoboRio much easier.

**Comment by jkoritzinsky** [comment]
Go for it!

**Comment by ThadHouse** [comment]
Closes by #40
