### ISSUE TITLE
Unlist 2016 (pre-Semantic Versioning) packages

### ISSUE THREAD

**Issue by jkoritzinsky** [robotdotnet/NetworkTables#65]
Until we unlist these packages, they will always be selected as the most recent package because the major version will be much higher than our newest Semantic Versioning packages.

**Comment by ThadHouse** [comment]
Yeah my plan was to unlist them when I do the release, probably on Friday. That was part of the issue moving from yearly packages to versioned packages, but definitely worth it.

**Comment by jkoritzinsky** [comment]
Sounds good to me!

**Comment by ThadHouse** [comment]
Release version 3.1.5 has been pushed, and the old releases have all been unlisted.
